# Generated by Django 5.2.11 on 2026-02-18 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting for Player'), ('active', 'Active'), ('finished', 'Finished')], default='waiting', max_length=20)),
                ('current_turn', models.BooleanField(default=True)),
                ('fen_position', models.CharField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', max_length=100)),
                ('quantum_mode', models.BooleanField(default=False)),
                ('move_history', models.JSONField(default=list)),
                ('quantum_pieces', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player_black', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_black', to=settings.AUTH_USER_MODEL)),
                ('player_white', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_white', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_number', models.IntegerField()),
                ('is_white_move', models.BooleanField()),
                ('move_type', models.CharField(choices=[('normal', 'Normal Move'), ('split', 'Split (Quantum)'), ('entangle', 'Entangle (Quantum)'), ('measure', 'Measurement (Quantum')], default='normal', max_length=20)),
                ('from_square', models.IntegerField()),
                ('to_square', models.IntegerField()),
                ('promotion', models.CharField(blank=True, max_length=1, null=True)),
                ('san', models.CharField(max_length=10)),
                ('fen_after', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='quantum_chess.game')),
            ],
            options={
                'ordering': ['move_number', 'is_white_move'],
            },
        ),
        migrations.CreateModel(
            name='QuantumPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_type', models.CharField(choices=[('P', 'Pawn'), ('N', 'Knight'), ('B', 'Bishop'), ('R', 'Rook'), ('Q', 'Queen'), ('K', 'King')], max_length=1)),
                ('is_white', models.BooleanField()),
                ('quantum_states', models.JSONField(default=dict)),
                ('entangled_with', models.JSONField(default=list)),
                ('is_measured', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantum_pieces_data', to='quantum_chess.game')),
            ],
        ),
    ]
