# Generated by Django 5.2.11 on 2026-02-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantum_chess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='measurement_history',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='game',
            name='pending_measurement',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
